routes/web.php
<?php


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::resource('/', 'DashboardController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('departments', 'DepartmentsController');
    Route::resource('joblevels', 'JobLevelController');
    Route::resource('users', 'UsersController');
    Route::resource('tasks', 'TasksController');
    Route::resource('mytasks', 'MyTasksController');
    Route::get('download/{file}', [
        'uses' => 'TasksController@download',
        'as' => 'documents.download'
    ]);
    Route::get('departmental', [
        'uses' => 'TasksController@departments',
        'as' => 'tasks.departments'
    ]);
    Route::get('depart/{id}', [
        'uses' => 'TasksController@viewDepartmentTasks',
        'as' => 'tasks.departs'
    ]);
    Route::post('reassign/{id}', [
        'uses' => 'TasksController@reassign',
        'as' => 'tasks.taskuser'
    ]);
    Route::get('employee/{id}', [
        'uses' => 'TasksController@reassignTo',
        'as' => 'tasks.employee'
    ]);
    Route::get('follow/{id}', [
        'uses' => 'TasksController@follow',
        'as' => 'follow.task'
    ]);
    Route::get('followuser/{id}', [
        'uses' => 'UsersController@followuser',
        'as' => 'follow.user'
    ]);
    Route::post('newcomment/{id}', [
        'uses' => 'MyTasksController@newComment',
        'as' => 'comments.new'
    ]);
});
Route::get('{provider}/auth', [
    'uses' => 'SocialsController@auth',
    'as' => 'social.auth'
]);
Route::get('{provider}/redirect', [
    'uses' => 'SocialsController@auth_callback',
    'as' => 'social.callback'
]);
Route::get('/home', 'HomeController@index')->name('home');

app/Task.php
<?php

namespace App;

use App\AccessLevel;
use App\Category;
use App\Comment;
use App\Department;
use App\FollowTask;
use App\Priority;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['title', 'category_id', 'due_date', 'priority_id', 'description', 'access_level_id',
        'document','assign_to','created_by','done','status','send_email_after','recur_daily','recur_days'];

    function category()
    {
        return $this->belongsTo(Category::class);
    }

    function departments()
    {
        return $this->belongsToMany('App\Department');
    }

    function users()
    {
        return $this->belongsToMany('App\User');
    }

    function access_level()
    {
        return $this->belongsTo(AccessLevel::class);
    }


    public function priority()
    {
        return $this->belongsTo(Priority::class);
    }
    public function employee(){
        return $this->belongsTo('App\User','assign_to');
    }
    public function comments(){
        return $this->belongsToMany(Comment::class);
    }

    public function followtasks(){
        return $this->belongsToMany(FollowTask::class);
    }

    public function getTitleAttribute($title)
    {
        return ucfirst($title);
    }
    public function getStatusAttribute($status)
    {
        return ucfirst($status);
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\AccessLevel;
use App\Category;
use App\Comment;
use App\Department;
use App\FollowTask;
use App\Priority;
use App\Task;
use App\User;
use Illuminate\Http\Request;
use App\Notifications\NewTaskAdded;
use Notification;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if(Auth::user()->position->name == 'Senior'):
               return view('tasks.index')->with('tasks', Task::orderBy('created_at','desc')->get());
              endif;

         return view('tasks.index')->with('tasks',Task::whereAccessLevelId(1)
                      ->orWhere('created_by',Auth::id())->orderBy('created_at','desc')
                      ->get());

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tasks.create')->with('categories', Category::all())
            ->with('priorities', Priority::all())
            ->with('employees', User::all())
            ->with('departments', Department::all())
            ->with('access_levels', AccessLevel::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,
            ['title' => 'required',
                'due_date' => 'required',
                'priority_id' => 'required',
                'category_id' => 'required',
                'user_id' => 'required',
                'description' => 'required',
                'access_level_id' => 'required',
                'department_id' => 'required',
                'assign_to' => 'required',


            ]
        );

        $document_name = '';
        if ($request->hasFile('document')) {
            $document = $request->file('document');
            $document_name = time() . $document->getClientOriginalName();
            $document->move('uploads/documents', $document_name);

        }

        $task = Task::create([
            'title' => $request->get('title'),
            'due_date' => $request->get('due_date'),
            'priority_id' => $request->get('priority_id'),
            'category_id' => $request->get('category_id'),
            'description' => $request->get('description'),
            'access_level_id' => $request->get('access_level_id'),
            'created_by' => Auth::id(),
            'assign_to' => $request->get('assign_to'),
            'document' => $document_name,
            'recur_days' => $request->get('recur_days'),
            'recur_daily' => $request->get('recur_days') ? '' : $request->get('recur_daily'),
            'send_email_after' => $request->get('send_email_after'),

        ]);
       
        $task->departments()->attach($request->get('department_id'));
        $task->users()->attach($request->get('user_id'));


        $user_group = array();

        foreach($request->get('user_id') as $ids):
            array_push($user_group,User::find($ids));
        endforeach;

         foreach($request->get('department_id') as $d_ids):
             array_push($user_group,User::whereDepartmentId($d_ids)->first());
         endforeach;

        Notification::send($user_group, new NewTaskAdded($task));
                    
        Session::flash('success', 'You have successfully added a task');
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('tasks.show')->with('task', Task::findOrfail($id))
            ->with('categories', Category::all())
            ->with('priorities', Priority::all())
            ->with('employees', User::all())
            ->with('departments', Department::all())
            ->with('access_levels', AccessLevel::all())
            ->with('comments',Comment::orderBy('created_at','desc')->whereTaskId($id)->get());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('tasks.edit')->with('task', Task::findOrfail($id))
            ->with('categories', Category::all())
            ->with('priorities', Priority::all())
            ->with('employees', User::all())
            ->with('departments', Department::all())
            ->with('access_levels', AccessLevel::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,
            ['title' => 'required',
                'due_date' => 'required',
                'priority_id' => 'required',
                'category_id' => 'required',
                'user_id' => 'required',
                'description' => 'required',
                'access_level_id' => 'required',
                'department_id' => 'required',
                'assign_to' => 'required',

            ]

        );
        $task = Task::findOrFail($id);

        if ($request->hasFile('document')) {
            $document = $request->get('document');
            $document_name = time() . $document->getClientOriginalName();
            $document->move('uploads/documents', $document_name);
            $task->document = $document_name;

        }
        $task->title = $request->get('title');
        $task->due_date = $request->get('due_date');
        $task->priority_id = $request->get('priority_id');
        $task->category_id = $request->get('category_id');
        $task->description = $request->get('description');
        $task->access_level_id = $request->get('access_level_id');
        $task->assign_to = $request->get('assign_to');
        $task->save();

        $task->departments()->sync($request->get('department_id'));
        $task->users()->sync($request->get('user_id'));

        Session::flash('success', 'You successfully updated a task');
        return redirect()->route('tasks.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Task::destroy($id);

        Session::flash('success', 'You successfully deleted a task');
        return redirect()->back();
    }

    public function download($file_name)
    {
        $file_path = public_path('uploads/documents/' . $file_name);
        return response()->download($file_path);
    }

    public function departments()
    {

        return view('tasks.departments')->with('departments',Department::all());
    }

    public function  viewDepartmentTasks($id){

       return view('tasks.department_tasks')->with('departments',Department::findOrFail($id));

    }
    public function reassignTo($id){

       return view('tasks.reassign')->with('task',Task::findOrFail($id))->with('users',User::all());
    }
    public function reassign()
    {
     $this->validate(request(),['assign_to' => 'required']);

     $task = Task::findOrFail(request()->get('id'));
     $task->assign_to = request()->get('assign_to');
     $task->save();

     Session::flash('success','Task succesfully updated.');
     return redirect()->route('tasks.index');

    }

    public function follow($id)
    {

     FollowTask::create([
         'task_id' => $id,
         'user_id' => Auth::id()
     ]);

     Session::flash('success','Successfully followed a task.');
     return redirect()->route('tasks.index');
    }


}

resources/views/tasks/create.blade.php
@extends('layouts.layout')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">

                <div class="panel panel-heading">New Task</div>

                <div class="panel panel-body">

                    <form action="{{route('tasks.store')}}" method="post" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="row">
                            <div class="col-md-6">


                                <div class="form-group">
                                    <label for="title">Title</label>
                                    <input type="text" class="form-control" name="title" placeholder="Title">
                                </div>
                                <div class="form-group">
                                    <label for="category">Category</label>
                                    <select name="category_id" id="category_id" class="form-control">
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                    </select>

                                </div>
                                <div class="form-group">
                                    <label for="priority">Priority</label>
                                    <select name="priority_id" id="priority_id" class="form-control">
                                        @foreach($priorities as $priority)
                                            <option value="{{$priority->id}}">{{$priority->name}}</option>
                                        @endforeach
                                    </select>

                                </div>

                                <div class="form-group">
                                    <label for="due_date">Due Date</label>
                                    <input type="text" class="form-control" id="due_date" name="due_date">
                                </div>

                                <div class="form-group">
                                    <label for="file">Attach File</label>
                                    <input type="file" class="form-control" name="document">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" id="repetitive">
                                        Repetitive Task ?
                                    </label>
                                </div>
                                <div class="showRecur" style="display: none">
                                    <div class="form-group">
                                        <label for="title">Recurrence Days</label>
                                        <select name="recur_days" id="recur_days" class="form-control">
                                            <option value="">Choose a day</option>
                                            <option value="mondays">Mondays</option>
                                            <option value="tuesdays">Tuesdays</option>
                                            <option value="wednesdays">Wednesdays</option>
                                            <option value="thursdays">Thursdays</option>
                                            <option value="fridays">Fridays</option>
                                            <option value="saturdays">Saturdays</option>
                                            <option value="sundays">Sundays</option>
                                        </select>
                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="recur_daily" id="recur_daily" value="1">
                                            Recur Daily ?
                                        </label>
                                    </div>
                                </div>

                                <div class="form-group showRecurdaily">
                                    <label for="send_email_after">Send Email After(days)</label>
                                    <input type="number" class="form-control" name="send_email_after" placeholder="0">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="department">Tag Department(s)</label>
                                        <select name="department_id[]" id="department_id" class="form-control" multiple="multiple">
                                            @foreach($departments as $department)
                                                <option value="{{$department->id}}">{{$department->name}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="assign_to">Tag Employee(s)</label>
                                        <select name="user_id[]" id="user_id" class="form-control" multiple="multiple">
                                            @foreach($employees as $employee)
                                                <option value="{{$employee->id}}">{{$employee->first_name .' '.$employee->last_name}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="access level">Access Level</label>
                                    <select name="access_level_id" id="access_level_id" class="form-control input-sm">
                                        @foreach($access_levels as $level)
                                            <option value="{{$level->id}}">{{$level->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="access level">Assign To</label>
                                    <select name="assign_to" id="assign_to" class="form-control input-sm">
                                        @foreach($employees as $emp)
                                            <option value="{{$emp->id}}">{{$emp->first_name .' '.$emp->last_name}}</option>
                                        @endforeach
                                    </select>
                                </div>


                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea name="description" id="description" cols="6" rows="6" class="form-control"></textarea>

                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit"><i class="fa fa-tasks"> Create Task</i></button>
                                </div>
                            </div>


                        </div>




                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

    <script>
        $(function () {
            $('#repetitive').click(function () {
              if ($(this).is(":checked"))  {
                  $('.showRecur').show();
                  $('.showRecurdaily').hide();
              }
              else {
                  $('.showRecur').hide();
                  $('.showRecurdaily').show();
              }
            });
        });

    </script>
    @stop

resources/views/tasks/department_tasks.blade.php
@extends('layouts.layout')

@section('content')

    <a href="{{route('tasks.create')}}" class="btn btn-primary btn-sm pull-right"><i class="fa fa-user-plus">Add New
            Task</i></a>

    <table class="table table-striped table-bordered" id="table">

        <thead>
        <tr>

            <th class="text-center">#</th>
            <th class="text-center">Title</th>
            <th class="text-center">Category</th>
            <th class="text-center">Priority</th>
            <th class="text-center">Done %</th>
            <th class="text-center">Status</th>
            <th class="text-center">Due Date</th>
            <th class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>

        @foreach($departments->tasks()->whereAccessLevelId(1)->orderBy('created_at','desc')->get() as $task)
            <tr>
                <td>{{$task->id}}</td>
                <td>{{$task->title}}</td>
                <td>{{$task->category->name}}</td>
                <td>{{$task->priority->name}}</td>
                <td>{{$task->done}}</td>
                <td>{{$task->status}}</td>
                <td>{{$task->due_date}}</td>
                <td class="text-center">
                    @if(Auth::user()->id == $task->created_by || Auth::user()->position->name =='Senior')
                        <a href="{{route('tasks.edit',['id' => $task->id])}}" class="btn btn-success btn-xs"><i
                                    class="fa fa-pencil-square-o"></i></a>
                    @endif
                    <a href="{{route('tasks.show',['id' => $task->id])}}" class="btn btn-info btn-xs"><i
                                class="fa fa-eye"></i></a>
                    @if(Auth::user()->id == $task->created_by || Auth::user()->position->name =='Senior')
                        <form action="{{route('tasks.destroy',['id' => $task->id])}}" method="post"
                              style="display: inline-block">
                            {{csrf_field()}}
                            {{method_field('DELETE')}}
                            <button class="btn btn-danger btn-xs" type="submit"><i class="fa fa-trash-o"></i></button>

                        </form>
                    @endif

                </td>

            </tr>
        @endforeach
        </tbody>
    </table>


@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.layout')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">

                <div class="panel panel-heading">Edit Task</div>

                <div class="panel panel-body">

                    <form action="{{route('tasks.update',['id' => $task->id])}}" method="post"
                          enctype="multipart/form-data">
                        {{csrf_field()}}
                        {{method_field('PUT')}}
                        <div class="row">
                            <div class="col-md-6">


                                <div class="form-group">
                                    <label for="title">Title</label>
                                    <input type="text" class="form-control" name="title"
                                           placeholder="Title" value="{{$task->title}}">
                                </div>
                                <div class="form-group">
                                    <label for="category">Category</label>

                                    <select name="category_id" id="category_id" class="form-control">
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}" {{$task->category->id == $category->id ? 'selected="selected"' : ''}}>{{$category->name}}</option>
                                        @endforeach
                                    </select>

                                </div>
                                <div class="form-group">
                                    <label for="priority">Priority</label>

                                    <select name="priority_id" id="priority_id" class="form-control">
                                        @foreach($priorities as $priority)
                                            <option value="{{$priority->id}}" {{$task->priority->id == $priority->id ? 'selected="selected"' : ''}}>{{$priority->name}}</option>
                                        @endforeach
                                    </select>

                                </div>

                                <div class="form-group">
                                    <label for="due_date">Due Date</label>
                                    <input type="text" class="form-control" id="due_date" name="due_date"
                                           value="{{$task->due_date}}">
                                </div>


                                <div class="form-group">
                                    <label for="file">Attach File</label>
                                    <input type="file" class="form-control" name="document">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="department">Tagged Department(s)</label>


                                        <select name="department_id[]" id="department_id" class="form-control"
                                                multiple="multiple">
                                            @foreach ($task->departments as $dept)
                                                @foreach($departments as $department)
                                                    <option value="{{$department->id}}" {{$dept->id == $department->id ? 'selected="selected"' : ''}}>{{$department->name}}</option>
                                                @endforeach
                                            @endforeach

                                        </select>

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="user_id">Tagged Employee(s)</label>
                                        <select name="user_id[]" id="user_id" class="form-control" multiple="multiple">
                                            @foreach($task->users as $user)
                                            @foreach($employees as $employee)
                                                <option value="{{$employee->id}}" {{$user->id == $employee->id ? 'selected="selected"' : ''}}>{{$employee->first_name}}</option>
                                            @endforeach
                                                @endforeach
                                        </select>

                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="access level">Access Level</label>

                                    <select name="access_level_id" id="access_level_id" class="form-control input-sm">
                                        @foreach($access_levels as $level)
                                            <option value="{{$level->id}}" {{$task->access_level->id == $level->id ? 'selected="selected"' : ''}}>{{$level->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="access level">Assigned To</label>
                                       <select name="assign_to" id="assign_to" class="form-control input-sm">

                                        @foreach($employees as $emp)
                                            <option value="{{$emp->id}}" {{$task->employee->id == $emp->id ? 'selected="selected"' : ''}}>{{$emp->first_name .' '.$emp->last_name}}</option>
                                        @endforeach

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea name="description" id="description" cols="6" rows="6"
                                              class="form-control">{{$task->description}}</textarea>

                                </div>

                            </div>

                        </div>
                        <div class="form-group">
                            <button class="btn btn-success" type="submit" style="margin-top: -20px"><i class="fa fa-tasks"> Update Task</i>
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/tasks/index.blade.php
@extends('layouts.layout')

@section('content')

    <a href="{{route('tasks.create')}}" class="btn btn-primary btn-sm pull-right"><i class="fa fa-user-plus">Add New
            Task</i></a>


    <table class="table table-striped table-bordered" id="table">

        <thead>
        <tr>

            <th class="text-center">#</th>
            <th class="text-center">Title</th>
            <th class="text-center">Category</th>
            <th class="text-center">Priority</th>
            <th class="text-center">Done %</th>
            <th class="text-center">Status</th>
            <th class="text-center">Due Date</th>
            <th class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>

        @foreach($tasks as $task)
            <tr>
                <td>{{$task->id}}</td>
                <td>{{$task->title}}</td>
                <td>{{$task->category->name}}</td>
                <td>{{$task->priority->name}}</td>
                <td>{{$task->done}}</td>
                <td>{{$task->status}}</td>
                <td>{{$task->due_date}}</td>
                <td class="text-center">
                    @if(Auth::user()->id == $task->created_by || Auth::user()->position->name =='Senior')
                    <a href="{{route('tasks.edit',['id' => $task->id])}}" class="btn btn-success btn-xs"><i
                                class="fa fa-pencil-square-o"></i></a>
                        @endif
                    <a href="{{route('tasks.show',['id' => $task->id])}}" class="btn btn-info btn-xs"><i
                                class="fa fa-eye"></i></a>
                        @if(Auth::user()->id == $task->assign_to || Auth::user()->position->name =='Senior')
                        <a href="{{route('tasks.employee',['id' => $task->id])}}" class="btn btn-warning btn-xs"><i
                                    class="fa fa-repeat"></i></a>
                        @endif
                        @if(Auth::user()->id == $task->created_by || Auth::user()->position->name =='Senior')
                    <form action="{{route('tasks.destroy',['id' => $task->id])}}" method="post"
                          style="display: inline-block">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                        <button class="btn btn-danger btn-xs" type="submit"><i class="fa fa-trash-o"></i></button>

                    </form>
                            @endif

                </td>

            </tr>
        @endforeach
        </tbody>
    </table>


@endsection